job('Color-Palette-Via-DSL') {
    description('First Python job generated by the DSL on ${new Date()}, the project is a small Python project hosted on GitHub')
    scm {
        git('git@github.com:singiankay/color-palette-ai.git', 'master')
    }
    triggers {
        scm('* * * * *')
    }
}